### ISSUE TITLE
9 pin question

### ISSUE THREAD

**Issue by JulyIghor** [SequoiaSan/FlipperZero-WiFi-Scanner_Module#12]
I just have one question.
Why we can't use Flipper's 3.3V (9) pin instead but need AMS1117?

https://github.com/SequoiaSan/FlipperZero-WiFi-Scanner_Module-ESP8266/raw/main/rep_images/Schematics_2.jpg?raw=true

**Comment by SequoiaSan** [comment]
@JulyIghor 

Because of power consumption. If we'll have module attached for some period of time even when not in use it will draw Flipper's battery power.
We can power ON\OFF 5V bus, but not 3V3. If we turn OFF 3V3 we also will turn on power for SD card.

+ in first versions module init/start was done by powering the module.
In newer version it's not a case. Module init is done on app start and running on 3V3 is possible.
